[package]
name = "ai-chat-mcp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
http.workspace = true
rmcp.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
tokio.workspace = true
uuid.workspace = true
ai-chat-application = { path = "../application" }
ai-chat-domain = { path = "../domain" }
ai-chat-infrastructure = { path = "../infrastructure" }
ai-chat-shared = { path = "../shared" }
